// Command gendocs generates docs/cli-reference.md from the live Cobra command
// tree, so the reference can never drift from the actual flag surface the way
// a hand-maintained copy can (#241). Run via `make docs`; the contract CI job
// regenerates and diffs it the same way it does gofmt/go.mod.
package main

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/phenixblue/k8shark/cmd"
	"github.com/spf13/cobra"
	"github.com/spf13/cobra/doc"
)

const outPath = "docs/cli-reference.md"

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, "gendocs:", err)
		os.Exit(1)
	}
}

func run() error {
	root := cmd.RootCmd()

	// Registers the default "completion" (bash/zsh/fish/powershell) and
	// "help" subcommands, which otherwise only get added lazily inside
	// Execute() — never called here, since we walk the tree instead of
	// running it. Without this, completion/help would be silently missing
	// from the generated reference.
	root.InitDefaultCompletionCmd()
	root.InitDefaultHelpCmd()

	// Generate into a temp file in the same directory and rename into place
	// only after a successful Flush/Close, so a failure partway through
	// generation can't leave docs/cli-reference.md truncated.
	f, err := os.CreateTemp(filepath.Dir(outPath), ".cli-reference-*.md.tmp")
	if err != nil {
		return err
	}
	tmpPath := f.Name()
	defer os.Remove(tmpPath)
	w := bufio.NewWriter(f)

	fmt.Fprintln(w, "# CLI Reference")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "Generated from the live Cobra command tree by `make docs` (tools/gendocs) —")
	fmt.Fprintln(w, "do not edit by hand. Run `make docs` after changing any command or flag")
	fmt.Fprintln(w, "definition; CI's `contract` job fails if this file drifts from `cmd/`, the")
	fmt.Fprintln(w, "same way it fails on gofmt or `go.mod` drift.")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "See [docs/usage.md](usage.md) for a curated, worked-example walkthrough of")
	fmt.Fprintln(w, "the commands most people reach for first; this page is the exhaustive,")
	fmt.Fprintln(w, "always-accurate flag reference for all of them, including the ones")
	fmt.Fprintln(w, "usage.md doesn't cover in depth (`encrypt`, `decrypt`, `version`,")
	fmt.Fprintln(w, "`completion`) and every global flag.")
	fmt.Fprintln(w)

	if err := genCommand(w, root); err != nil {
		return err
	}
	if err := w.Flush(); err != nil {
		return err
	}
	if err := f.Close(); err != nil {
		return err
	}
	return os.Rename(tmpPath, outPath)
}

// linkHandler rewrites the cross-command links doc.GenMarkdown emits (e.g.
// "kshrk_capture.md", meant for GenMarkdownTree's one-file-per-command
// layout) into in-page anchors, since every command lands in this single
// file instead.
func linkHandler(link string) string {
	anchor := strings.TrimSuffix(link, ".md")
	anchor = strings.ToLower(strings.ReplaceAll(anchor, "_", "-"))
	return "#" + anchor
}

// genCommand writes cmd's section, then recurses into its children in the
// same order/filter cobra's own doc.GenMarkdownTree uses, so this matches
// what `kshrk help` itself would show.
func genCommand(w *bufio.Writer, c *cobra.Command) error {
	// DisableAutoGenTag suppresses GenMarkdown's own "Auto generated by
	// spf13/cobra on <date>" footer — checked per-command, not inherited —
	// which would otherwise make this file (and the CI drift check) change
	// every single day regardless of any real command/flag edit.
	c.DisableAutoGenTag = true
	if err := doc.GenMarkdownCustom(c, w, linkHandler); err != nil {
		return err
	}
	fmt.Fprintln(w)

	children := c.Commands()
	sort.Slice(children, func(i, j int) bool { return children[i].Name() < children[j].Name() })
	for _, child := range children {
		if !child.IsAvailableCommand() || child.IsAdditionalHelpTopicCommand() {
			continue
		}
		if err := genCommand(w, child); err != nil {
			return err
		}
	}
	return nil
}
